# Spring配置相关
spring:
  datasource:
    url: jdbc:mysql://43.138.185.20:3306/db_noob_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: db_noob_demo
    password: XCYXi8wPBS5nfbHz
    driver-class-name: com.mysql.cj.jdbc.Driver


