server:
  port: 8080
  # Spring配置相关
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

# MyBatis 配置
mybatis:
  type-aliases-package: com.noob.framework.transaction.entity
  configuration:
    map-underscore-to-camel-case: true

