# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /api

# spring相关配置
spring:
#  profiles:
#    active: test
  redis:
    host: localhost
    port: 6379

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_asyncflow  # db_mysql_base
    username: root
    password: 123456
    # druid 数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 1                                          # 最小连接数
      max-active: 2000                                     # 最大连接数(默认8)
      max-wait: 1000                                      # 获取连接时的最大等待时间
      min-evictable-idle-time-millis: 300000               # 一个连接在池中最小生存的时间，单位是毫秒（空闲时间）
      time-between-eviction-runs-millis: 60000             # 多久才进行一次检测需要关闭的空闲连接，单位是毫秒

# mybatis-plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
