# 项目名称
spring:
  application:
    name: springboot-mybatis-multiDatasource
  datasource:
    # 主数据库
    master:
      # 注意，整合多数据源时如果使用springboot默认的数据库连接池Hikari，指定连接数据使用的是jdbc-url而不是url属性
      jdbc-url: jdbc:mysql://43.138.185.20:3306/db_noob_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: db_noob_demo
      password: XCYXi8wPBS5nfbHz
      driver-class-name: com.mysql.cj.jdbc.Driver
    # 副数据库
    slave:
      # 注意，整合多数据源时如果使用springboot默认的数据库连接池Hikari，指定连接数据使用的是jdbc-url而不是url属性
      jdbc-url: jdbc:mysql://43.138.185.20:3306/db_noob_demo_bak?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: db_noob_demo_bak
      password: T8Ys27Cj3HjmHFKK
      driver-class-name: com.mysql.cj.jdbc.Driver

