# 应用服务 WEB 访问端口
server:
  port: 8081
  servlet:
    context-path: /api

# spring相关配置
spring:
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379

  # kafka 相关配置
  kafka:
    bootstrap-servers: localhost:9092  # 配置kafka连接信息（服务器地址、端口号等）
